use_frameworks!

target 'ChangellyAPI_Example' do
  platform :ios, 10.0

  pod 'CoinpaprikaAPI/Networking'
  pod 'ChangellyAPI', :path => '../'

  target 'ChangellyAPI_Tests' do
    inherit! :search_paths

    
  end
end
